combined wsl scripts and routed test logs to appropriate folder

diff --git a/scripts/build-configure b/scripts/build-configure
--- a/scripts/build-configure
+++ b/scripts/build-configure
@@ -5,23 +5,51 @@ usage() {
     echo "  -t: Build test files"
 }
 
+OS_NAME=$(uname)
 option_given=0
 
-while getopts ":t" opt; do
-    option_given=1
+if [[ "$OS_NAME" == "Darwin" ]]; then
+    while getopts ":t" opt; do
+        option_given=1
 
-    case $opt in
-        t)
-            cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake -DBUILD_TESTING=ON
-            ;;
-        \?)
-            echo "Invalid option: -$opt" >&2
-            usage
-            ;;
-    esac
-done
+        case $opt in
+            t)
+                cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake -DBUILD_TESTING=ON
+                ;;
+            \?)
+                echo "Invalid option: -$opt" >&2
+                usage
+                ;;
+        esac
+    done
 
-if [ $option_given -eq 0 ]; then
-    # create toolchain file for build
-    cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake
+    if [ $option_given -eq 0 ]; then
+        # create toolchain file for build
+        cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake
+    fi
+elif [[ "$OS_NAME" == "Linux" ]]; then
+    while getopts ":t" opt; do
+        option_given=1
+
+        case $opt in
+            t)
+                cmake -S /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion \
+                    -B /home/its-geoff/wsl_build/course-companion/build \
+                    -DBUILD_TESTING=ON
+                ;;
+            \?)
+                echo "Invalid option: -$opt" >&2
+                usage
+                ;;
+        esac
+    done
+
+    if [ $option_given -eq 0 ]; then
+        # create toolchain file for build
+        cmake -S /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion \
+            -B /home/its-geoff/wsl_build/course-companion/build
+    fi
+else
+    echo "Unknown OS: $OS_NAME"
+    exit 1
 fi
diff --git a/scripts/setup-deps b/scripts/setup-deps
--- a/scripts/setup-deps
+++ b/scripts/setup-deps
@@ -1,4 +1,52 @@
 #!/bin/bash
 
-# install missing dependencies
-conan install .. --build=missing -of build
+usage() {
+    echo "Usage: setup-deps [-t]"
+    echo "  -t: Output to build_test"
+}
+
+OS_NAME=$(uname)
+option_given=0
+
+if [[ "$OS_NAME" == "Darwin" ]]; then
+    while getopts ":t" opt; do
+        option_given=1
+
+        case $opt in
+            t)
+                conan install .. --build=missing -of build_test
+                ;;
+            \?)
+                echo "Invalid option: -$opt" >&2
+                usage
+                ;;
+        esac
+    done
+
+    if [ $option_given -eq 0 ]; then
+        # create toolchain file for build
+        conan install .. --build=missing -of build_main
+    fi
+elif [[ "$OS_NAME" == "Linux" ]]; then
+    while getopts ":t" opt; do
+        option_given=1
+
+        case $opt in
+            t)
+                conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_test
+                ;;
+            \?)
+                echo "Invalid option: -$opt" >&2
+                usage
+                ;;
+        esac
+    done
+
+    if [ $option_given -eq 0 ]; then
+        # create toolchain file for build
+        conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_main
+    fi
+else
+    echo "Unknown OS: $OS_NAME"
+    exit 1
+fi
diff --git a/scripts/wsl-setup-deps b/scripts/wsl-setup-deps
--- a/scripts/wsl-setup-deps
+++ b/scripts/wsl-setup-deps
@@ -1,4 +1,29 @@
 #!/bin/bash
 
-# install missing dependencies
-conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build
+#!/bin/bash
+
+usage() {
+    echo "Usage: setup-deps [-t]"
+    echo "  -t: Output to build_test"
+}
+
+option_given=0
+
+while getopts ":t" opt; do
+    option_given=1
+
+    case $opt in
+        t)
+            conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_test
+            ;;
+        \?)
+            echo "Invalid option: -$opt" >&2
+            usage
+            ;;
+    esac
+done
+
+if [ $option_given -eq 0 ]; then
+    # create toolchain file for build
+    conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_main
+fi
