added test-only configurations for shell scripts

diff --git a/scripts/build-configure b/scripts/build-configure
--- a/scripts/build-configure
+++ b/scripts/build-configure
@@ -1,4 +1,27 @@
 #!/bin/bash
 
-# create toolchain file for build
-cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake
+usage() {
+    echo "Usage: build-configure [-t]"
+    echo "  -t: Build test files"
+}
+
+option_given=0
+
+while getopts ":t" opt; do
+    option_given=1
+
+    case $opt in
+        t)
+            cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake -DBUILD_TESTING=ON
+            ;;
+        \?)
+            echo "Invalid option: -$opt" >&2
+            usage
+            ;;
+    esac
+done
+
+if [ $option_given -eq 0 ]; then
+    # create toolchain file for build
+    cmake -S .. -B build -DCMAKE_TOOLCHAIN_FILE=build/build/conan_toolchain.cmake
+fi
diff --git a/scripts/make-build b/scripts/make-build
--- a/scripts/make-build
+++ b/scripts/make-build
@@ -1,3 +1,32 @@
 #!/bin/bash
 
 cmake --build .
+
+usage() {
+    echo "Usage: make-build [-mt]"
+    echo "  -m: Only build main files"
+    echo "  -t: Only build test files"
+}
+
+option_given=0
+
+while getopts ":mt" opt; do
+    option_given=1
+
+    case $opt in
+        m)
+            cmake --build . --target CourseCompanion_lib
+            ;;
+        t)
+            cmake --build . --target tests
+            ;;
+        \?)
+            echo "Invalid option: -$opt" >&2
+            usage
+            ;;
+    esac
+done
+
+if [ $option_given -eq 0 ]; then
+    cmake --build .
+fi
